<?php
$newInsertID="";$currentURl="http://".$_SERVER["HTTP_HOST"]."".$_SERVER["REQUEST_URI"];
if($form<>""){
	$systemForm="common/forms/".$form.".php";
	if(file_exists($systemForm)){
		include($systemForm);
	}else{
		?><script>window.location="?<?=$form?>";</script><?
	}
}
if($newInsertID<>""){
	?><script>window.location="<?=$currentURl?>";</script><?
}
?>